<?php
    $catIds = explode(',', $this->getIds());

    $categories = array();
    foreach($catIds as $catId) {
    $category = Mage::getModel('catalog/category')->load($catId); 
    $categories[$category->getName()] = array(
        'url' => $category->getUrl(),
        'img' => $category->getCustomAttribute()
    );
}

ksort($categories, SORT_STRING);
?>
<ul class="categories-custom">
    <?php if($category->getIsActive()): ?>
    <?php foreach($categories as $name => $data): ?>
        <li>
            <div class="imageWrapper">
            <a href="<?php echo $data['url']; ?>" title="<?php echo $name; ?>" alt="<?php echo $name; ?>">
                
                <div class="image-svg"><?php echo $data['img']; ?></div>

            </a>
            </div>
            <a href="<?php echo $data['url']; ?>" title="<?php echo $name; ?>" alt="<?php echo $name; ?>">
                <span class="name"><?php echo $name; ?></span>
            </a>
        </li>   
    <?php endforeach; ?>
    <?php endif; ?>
</ul>