            <div class="block block-subscribe">
                <div class="block-title">
                    <strong><span><?php echo $this->__('Newsletter') ?></span></strong>
                </div>
                <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
                    <div class="block-content">
                        <div class="form-subscribe-header">
                            <label for="newsletter"><?php echo $this->__('Sign Up for Our Newsletter:') ?></label>
                        </div>
                        <div class="input-box">
                        <input type="email" autocapitalize="off" placeholder="<?php echo __('Inserisci la tua e-mail') ?>" autocorrect="off" spellcheck="false" name="email" id="newsletter" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Sign up for our newsletter')) ?>" class="input-text required-entry validate-email" />
                        </div>
                        <div class="actions">
                            <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Subscribe')) ?>" class="button"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
                        </div>
                        <div class="poly">
                            <p class="policy">
                                
                                <span><input class="required-entry" name="policy" type="checkbox">Ho letto e accetto l’ <ins>informativa sulla privacy policy</ins></a></span>
                            </p>
                            <p class="policy">
                                
                                <span><input class="required-entry" name="policy 123" type="checkbox">Acconsento al trattamento di cui al punto 3 lettera f dell’ <ins>informativa sulla privacy </ins></a></span>
                            </p>
                        </div>
                    </div>
                </form>
                <script type="text/javascript">
                //<![CDATA[
                    var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
                //]]>
                </script>
            </div>
